//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dental_Clinic_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public string drug1 { get; set; }
        public int prescp_no { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
