//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dental_Clinic_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptionist
    {
        public int recep_id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Phone { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string recep_address { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
